on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      action:
        description: 'Action to run'
        required: true
        type: string
      
jobs:
  run-quality-checks:
    runs-on: ubuntu-latest
    if: ${{ inputs.python-version == '3.9' || inputs.python-version == '3.10' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run quality checks
        run: |
          if [ "${{ inputs.action }}" == "lint" ]; then
            flake8 src test
          elif [ "${{ inputs.action }}" == "test" ]; then
            PYTHONPATH= src pytest
          else
            echo "Invalid action specified."
            exit 1
          fi

  unsupported-python:
    runs-on: ubuntu-latest
    if: ${{ inputs.python-version != '3.9' && inputs.python-version != '3.10' }}
    steps:
      - name: Unsupported Python Version
        run: |
          echo "The specified Python version ${{ inputs.python-version }} is not supported. Only 3.9 and 3.10 are allowed."
          exit 1

